### ISSUE TITLE
When running Shiny from SublimeStudio, working directory not set

### ISSUE THREAD

**Issue by marks** [christophsax/SublimeStudio#1]
Screenshot attached. It seems to always default to my home directory

![r_console](https://cloud.githubusercontent.com/assets/34566/9567817/664644a0-4f06-11e5-96f3-bf57f89e682c.png)

**Comment by christophsax** [comment]
If you want to run a Shiny app, set the directory of your shiny app (the
one with `ui.R` and `server.R`) your 'R-directory' (`shift`+`ctrl/cmd`+`H`). Press `shift`+`ctrl/cmd`+`A`
to run the app.

I updated the readme to give some explanations.

**Comment by marks** [comment]
Got it. Thanks
