### ISSUE TITLE
how to install it on separate server 

### ISSUE THREAD

**Issue by dipenpatel235** [christophsax/SublimeStudio#2]
how to install it on separate server ?

**Comment by christophsax** [comment]
Don't know what you mean. This is an Editor plug in, and you use it with Sublime Text, usually locally.

**Comment by dipenpatel235** [comment]
ok..
i want to setup your plugin as server and using url i can able to write code and compile it similar likr RStudio.

it is mine actual requirements.

In Rstudio have limitation only one user  can able to access it.

**Comment by christophsax** [comment]
I don't think that is possible.
